"""The C# oracle is a TRANSCRIPTION — gate it against the real decompile.

``dev/decompiler/formcztv_init.py`` is a hand-written Python copy of
``FormCZTVInit`` (``TRCC.CZTV/FormCZTV.cs:858``).  Every device audit compares
our shipping code against *that copy*, never against the ``.cs`` itself — so a
branch the transcriber missed is not a disagreement, it is **silence**, and
silence reads as agreement.

Its own docstring records what that already cost::

    The previous revision was transcribed from the 2.0.3 tree ... not merely
    stale, it was *load-bearingly wrong*: it had no ``mySubMode`` at all ...
    and it reported AGREE on a device we now know we ship 180 degrees out.
    It was also missing the pm 13/15/16/17/18/50/63/66/68/69 branches.

    A stale oracle is worse than no oracle: it manufactures agreement.

Nothing checked that claim mechanically, so the same failure was free to
recur.  This does.  ``dev/decompiler/control-flow.json`` is generated by
``extract_control_flow.py``, which walks every line of every ``.cs`` and cannot
sample or skip — so it is the one machine-read view of the real C#, and the
right thing to hold the transcription against.

**This currently PASSES, and that is the point.**  It is a ratchet on a
correct state, not a bug report: it fails the day someone re-transcribes,
bumps ``ORACLE_RELEASE``, or adds a branch to one side only.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
# Resolved at MODULE scope, exactly as test_oracle_version does, and for the
# same reason: the suite sandboxes ``HOME`` in a function-scoped fixture, so a
# ``~``-derived path imported inside a test body resolves under the pytest
# tmpdir and the check skips itself on a machine that HAS the decompile.
# Collection runs first; module scope is the only place this is true.
sys.path.insert(0, str(_REPO / "dev" / "decompiler"))
from core.csharp import (  # noqa: E402  # pyright: ignore[reportMissingImports]
    DECOMPILE_ROOT,
)

#: The C# file, spelled ONCE.  ``control-flow.json`` keys on this relative
#: path and the decompile holds it at that path under the root, so the two
#: uses derive from one literal rather than agreeing by coincidence.
_CS_FILE = "TRCC.CZTV/FormCZTV.cs"
_CS_METHOD = "FormCZTVInit"
_CS_SOURCE = DECOMPILE_ROOT / _CS_FILE
_CONTROL_FLOW = _REPO / "dev" / "decompiler" / "control-flow.json"
_TRANSCRIPTION = _REPO / "dev" / "decompiler" / "formcztv_init.py"


def _pm_values(text: str) -> set[int]:
    """Every PM the text branches on, in either shape.

    The C# writes ``pm == 9 || pm == 11``; the transcription collapses that to
    ``pm in (9, 11)``.  Reading only ``==`` sees the first form and half of the
    second, which manufactures a diff out of a faithful copy -- that mistake is
    why this helper is shared by both sides rather than written twice.
    """
    found = {int(n) for n in re.findall(r"\bpm\s*==\s*(\d+)", text)}
    for group in re.findall(r"\bpm\s+in\s*\(([0-9,\s]+)\)", text):
        found.update(int(n) for n in re.findall(r"\d+", group))
    return found


def _executable_lines(source: str) -> str:
    """The transcription's CODE, minus comments and citation strings.

    ``st.hit(...)`` lines quote the C# condition as human-readable text, so
    counting them would let a branch that is only *described* pass as a branch
    that is *implemented*.
    """
    return "".join(
        line for line in source.splitlines(keepends=True)
        if not line.lstrip().startswith(("#", "st.hit", '"', "'"))
    )


def _csharp_pms() -> set[int]:
    data = json.loads(_CONTROL_FLOW.read_text(encoding="utf-8"))
    methods = data[_CS_FILE]
    init = next(m for m in methods if m["name"] == _CS_METHOD)
    return _pm_values(json.dumps(init["branches"]))


def test_control_flow_map_is_present() -> None:
    """The machine-read view of the C# is committed, not regenerated on demand.

    Without it this whole file would skip, and a gate that skips is a gate
    that is not there.
    """
    assert _CONTROL_FLOW.is_file(), (
        f"{_CONTROL_FLOW} is missing — regenerate it with "
        "`python3.12 dev/decompiler/extract_control_flow.py`"
    )
    assert _csharp_pms(), (
        f"no `pm ==` branches found for {_CS_METHOD} in {_CS_FILE} — the "
        "extractor's output shape changed and this gate is now blind"
    )


def test_every_csharp_pm_branch_is_transcribed() -> None:
    """No branch exists in the C# that the transcription silently drops."""
    missing = sorted(_csharp_pms() - _pm_values(_executable_lines(
        _TRANSCRIPTION.read_text(encoding="utf-8"))))
    assert not missing, (
        f"{_CS_METHOD} branches on PM {missing} and "
        f"{_TRANSCRIPTION.name} does not. Every device audit runs against the "
        "transcription, so these panels are not 'disagreeing' — they are "
        "unrepresented, and the audit will report AGREE for them forever."
    )


def test_the_transcription_invents_no_branch() -> None:
    """And nothing is transcribed that the C# does not actually test.

    The opposite failure and the quieter one: a PM the real program never
    branches on, answered confidently by our copy of it.
    """
    extra = sorted(_pm_values(_executable_lines(
        _TRANSCRIPTION.read_text(encoding="utf-8"))) - _csharp_pms())
    assert not extra, (
        f"{_TRANSCRIPTION.name} branches on PM {extra}, which {_CS_METHOD} "
        "never tests. Our oracle would answer for hardware the C# has no "
        "opinion about."
    )


@pytest.mark.skipif(
    not _CS_SOURCE.is_file(),
    reason=f"no decompile at {DECOMPILE_ROOT} — set TRCC_DECOMPILE",
)
def test_control_flow_map_still_matches_the_live_decompile() -> None:
    """Gate the ROUND TRIP, not just the half we committed.

    ``control-flow.json`` is itself a generated artifact.  Holding the
    transcription against a stale artifact would re-create the exact failure
    this file exists to prevent, one level down.  When the decompile is on
    this machine, re-read the real ``.cs`` and confirm the committed map still
    describes it.  Absent (CI, a fresh clone), skip -- same stance as
    ``test_oracle_version``.
    """
    text = _CS_SOURCE.read_text(encoding="utf-8", errors="replace")
    start = text.index(f"{_CS_METHOD}(")
    # The method's own body only — the next member starts at one tab, and
    # ILSpy output is regularly indented (the extractor leans on this too).
    body = text[start:]
    end = re.search(r"\n\t(?:private|public|protected|internal)\s", body)
    if end:
        body = body[:end.start()]

    live = _pm_values(body)
    committed = _csharp_pms()
    assert live == committed, (
        f"control-flow.json says {_CS_METHOD} branches on PM "
        f"{sorted(committed)}, the decompile on disk says {sorted(live)}. "
        "The committed map is stale — regenerate it with "
        "`python3.12 dev/decompiler/extract_control_flow.py`."
    )


# =========================================================================
# Field INITIALISERS — the state the branches start from
# =========================================================================
#
# The checks above gate CONTROL FLOW: every PM the C# branches on is
# transcribed, none is invented, and the committed map still describes the live
# .cs.  None of them can see a field's DEFAULT VALUE, because a field no branch
# assigns appears in no branch.
#
# That is exactly when the default is load-bearing.  A fingerprint that falls
# through every arm of ``SetThemeInfo_ThemeML`` is answered entirely by the
# initialiser, so a wrong one is not a rounding error — it is the whole answer.
#
# Measured 2026-09-20: ``CztvState.ThemeML`` was transcribed as ``"240320\\"``
# and annotated "C# field initialiser: PORTRAIT".  ``FormCZTV.cs:468`` says
# ``private string ThemeML = "320240\\";`` — LANDSCAPE, transposed, and the
# string ``240320`` is never assigned as a catalog anywhere in the decompile.
# Cost: **Mjolnir 320x240 pm5 (#176) was reported as a device divergence for as
# long as that line existed.** It matches. The audit was accusing our shipping
# code, and the reason the row looked mysterious — 320x240 is not among the
# nine resolutions the C# mount-tests — is that no mount rule was ever involved.

#: Deliberate divergences, each with the C# line that justifies it.  The same
#: stance as ``audit_devices._SEMANTIC_SPLIT``: not an escape hatch, one
#: verified case, and everything else compared directly.
_DELIBERATE_DEFAULTS: dict[str, str] = {
    # The C# initialises 0 (FormCZTV.cs:466), then its settings LOADER writes
    # -1 when there is no persisted value (:1216, :1225), and
    # SetThemeInfo_ThemeML branches on ``themeDirection == -1`` to mean FIRST
    # BOOT (:1267, :1291, :1358, :1374, :1398).  This transcription simulates
    # onboarding, so it starts at the post-load first-boot state on purpose.
    # It is spelled as the named constant ``FIRST_BOOT``, not a bare -1 —
    # which is precisely why this one survived review and ThemeML did not.
    "themeDirection": "FormCZTV.cs:466 initialises 0; the loader sets -1 for "
                      "first boot (:1216/:1225) and the selector branches on "
                      "it (:1267…). We model onboarding, so we start at -1.",
}


def _csharp_field_initialisers(text: str) -> dict[str, str]:
    """``{field: initialiser}`` for every non-const field the C# assigns inline.

    Class-level declarations only — indented one tab, which is how ILSpy emits
    members and what the control-flow extractor already relies on.  ``const``
    is excluded: those are the catalog name table, not mutable state.
    """
    found: dict[str, str] = {}
    pattern = re.compile(
        r"^\t(?:private|public|protected|internal)\s+"
        r"(?!const\b)(?:readonly\s+)?\w+\s+(\w+)\s*=\s*([^;]+);",
        re.M,
    )
    for name, value in pattern.findall(text):
        found[name] = value.strip()
    return found


@pytest.mark.skipif(
    not _CS_SOURCE.is_file(),
    reason=f"no decompile at {DECOMPILE_ROOT} — set TRCC_DECOMPILE",
)
def test_transcribed_field_defaults_match_the_decompile() -> None:
    """Every meaningful default in ``CztvState`` is the C#'s, or is declared.

    "Meaningful" = not falsy.  A ``False``/``0``/``""`` default carries no
    claim about the C# — it is what the type would be anyway — so comparing
    those would add noise without adding a guard.
    """
    import dataclasses

    from formcztv_init import (  # pyright: ignore[reportMissingImports]
        CztvState,
    )

    cs_text = _CS_SOURCE.read_text(encoding="utf-8", errors="replace")
    cs_fields = _csharp_field_initialisers(cs_text)
    assert "ThemeML" in cs_fields, (
        "the field-declaration parser found no ThemeML in "
        f"{_CS_FILE} — it has stopped matching ILSpy's output, so every "
        "check below would pass by finding nothing"
    )

    mismatches: list[str] = []
    for field in dataclasses.fields(CztvState):
        default = field.default
        if default is dataclasses.MISSING or not default:
            continue
        if field.name in _DELIBERATE_DEFAULTS:
            continue
        theirs = cs_fields.get(field.name)
        if theirs is None:
            continue          # a modelling field with no C# counterpart
        # Compare as the C# spells it: strings keep their quotes and escaped
        # trailing separator, ints are bare.
        ours = (f'"{default}"'.replace("\\", "\\\\")
                if isinstance(default, str) else str(default))
        if ours != theirs:
            mismatches.append(
                f"  {field.name}: transcription {ours}, "
                f"{_CS_FILE} says {theirs}")

    assert not mismatches, (
        "the transcription's field defaults disagree with the decompile.  A "
        "field no branch assigns is answered ENTIRELY by its default, so this "
        "is the whole answer for every fingerprint that falls through:\n"
        + "\n".join(mismatches)
        + "\n\nIf a difference is deliberate, add it to _DELIBERATE_DEFAULTS "
          "with the C# line that justifies it."
    )


@pytest.mark.skipif(
    not _CS_SOURCE.is_file(),
    reason=f"no decompile at {DECOMPILE_ROOT} — set TRCC_DECOMPILE",
)
def test_every_declared_divergence_still_names_a_real_field() -> None:
    """A declared exception must still correspond to a C# field.

    Otherwise a rename leaves an entry excusing a field that no longer exists,
    which silently exempts nothing and hides the next one that takes the name.
    """
    cs_fields = _csharp_field_initialisers(
        _CS_SOURCE.read_text(encoding="utf-8", errors="replace"))
    orphans = sorted(set(_DELIBERATE_DEFAULTS) - set(cs_fields))
    assert not orphans, (
        f"_DELIBERATE_DEFAULTS excuses field(s) {orphans} that no longer "
        f"exist in {_CS_FILE} — drop the entry or fix the name"
    )


# ── SetThemeInfo_ThemeML: the MOUNT method, gated the same way ──────────────
#
# Everything above gates ``FormCZTVInit`` and only its ``pm ==`` branches.  The
# mount lives in a different method (``SetThemeInfo_ThemeML``) and keys on a
# different byte (``pmSub``), so it sat outside this file entirely -- which is
# exactly how the transcription came to apply one hardcoded ``pmSub < 5`` to
# ten blocks that do not share a shape.  It reported a portrait mount for
# 1280x480 that the C# never performs, and put 1920x462's boundary one SUB byte
# low; both reached test_csharp_conformance as divergences against our own
# correct code.  Wrong method AND wrong axis: two reasons for one blind spot.

_CS_MOUNT_METHOD = "SetThemeInfo_ThemeML"


def _csharp_mount_thresholds() -> dict[str, int | None]:
    """``isWxH`` flag -> lowest pmSub meaning PORTRAIT, read from the C#.

    ``pmSub < N`` -> portrait from N.  ``pmSub <= N`` -> portrait from N+1.
    A block with no pmSub guard maps to ``None``: landscape on first boot
    whatever the SUB byte says.
    """
    data = json.loads(_CONTROL_FLOW.read_text(encoding="utf-8"))
    method = next(m for m in data[_CS_FILE] if m["name"] == _CS_MOUNT_METHOD)

    out: dict[str, int | None] = {}
    flag: str | None = None
    for branch in method["branches"]:
        cond = branch["condition"]
        if re.fullmatch(r"is\d+x\d+", cond):
            if flag is not None:
                out[flag] = None          # previous block had no pmSub guard
            flag = cond
            continue
        if flag is None:
            continue
        match = re.fullmatch(r"pmSub\s*(<=?)\s*(\d+)", cond)
        if match:
            value = int(match.group(2))
            out[flag] = value + 1 if match.group(1) == "<=" else value
            flag = None
        elif "pmSub" in cond:             # 1600x720's mySubMode switch
            flag = None
    if flag is not None:
        out[flag] = None
    return out


def test_every_mount_threshold_matches_the_decompile() -> None:
    """The transcription's per-block pmSub threshold IS the C#'s, row by row."""
    from formcztv_init import (  # pyright: ignore[reportMissingImports]
        _THEME_TOKENS,
    )

    theirs = _csharp_mount_thresholds()
    ours = {flag: portrait_from for flag, _, _, portrait_from, _ in _THEME_TOKENS}

    shared = ours.keys() & theirs.keys()
    assert shared, (
        f"no isWxH block matched between {_CS_MOUNT_METHOD} and _THEME_TOKENS "
        f"-- the reader is broken, not the data"
    )
    wrong = {f: (theirs[f], ours[f]) for f in sorted(shared)
             if theirs[f] != ours[f]}
    assert not wrong, (
        f"{_CS_MOUNT_METHOD} and the transcription disagree on the first "
        f"pmSub meaning PORTRAIT -- {{flag: (C#, ours)}}: {wrong}"
    )


def test_the_transcription_covers_every_guarded_mount_block() -> None:
    """No isWxH block the C# guards may be missing from the transcription."""
    from formcztv_init import (  # pyright: ignore[reportMissingImports]
        _SQUARE_TOKENS,
        _THEME_TOKENS,
    )

    theirs = _csharp_mount_thresholds()
    transcribed = ({flag for flag, *_ in _THEME_TOKENS}
                   | {flag for flag, _ in _SQUARE_TOKENS}
                   | {"is1600x720"})
    missing = sorted(f for f, threshold in theirs.items()
                     if threshold is not None and f not in transcribed)
    assert not missing, (
        f"{_CS_MOUNT_METHOD} applies a pmSub mount test to {missing}, which "
        f"the transcription does not model at all"
    )
