"""The C# oracle is a TRANSCRIPTION — gate it against the real decompile.

``dev/decompiler/formcztv_init.py`` is a hand-written Python copy of
``FormCZTVInit`` (``TRCC.CZTV/FormCZTV.cs:858``).  Every device audit compares
our shipping code against *that copy*, never against the ``.cs`` itself — so a
branch the transcriber missed is not a disagreement, it is **silence**, and
silence reads as agreement.

Its own docstring records what that already cost::

    The previous revision was transcribed from the 2.0.3 tree ... not merely
    stale, it was *load-bearingly wrong*: it had no ``mySubMode`` at all ...
    and it reported AGREE on a device we now know we ship 180 degrees out.
    It was also missing the pm 13/15/16/17/18/50/63/66/68/69 branches.

    A stale oracle is worse than no oracle: it manufactures agreement.

Nothing checked that claim mechanically, so the same failure was free to
recur.  This does.  ``dev/decompiler/control-flow.json`` is generated by
``extract_control_flow.py``, which walks every line of every ``.cs`` and cannot
sample or skip — so it is the one machine-read view of the real C#, and the
right thing to hold the transcription against.

**This currently PASSES, and that is the point.**  It is a ratchet on a
correct state, not a bug report: it fails the day someone re-transcribes,
bumps ``ORACLE_RELEASE``, or adds a branch to one side only.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
# Resolved at MODULE scope, exactly as test_oracle_version does, and for the
# same reason: the suite sandboxes ``HOME`` in a function-scoped fixture, so a
# ``~``-derived path imported inside a test body resolves under the pytest
# tmpdir and the check skips itself on a machine that HAS the decompile.
# Collection runs first; module scope is the only place this is true.
sys.path.insert(0, str(_REPO / "dev" / "decompiler"))
from core.csharp import (  # noqa: E402  # pyright: ignore[reportMissingImports]
    DECOMPILE_ROOT,
)

#: The C# file, spelled ONCE.  ``control-flow.json`` keys on this relative
#: path and the decompile holds it at that path under the root, so the two
#: uses derive from one literal rather than agreeing by coincidence.
_CS_FILE = "TRCC.CZTV/FormCZTV.cs"
_CS_METHOD = "FormCZTVInit"
_CS_SOURCE = DECOMPILE_ROOT / _CS_FILE
_CONTROL_FLOW = _REPO / "dev" / "decompiler" / "control-flow.json"
_TRANSCRIPTION = _REPO / "dev" / "decompiler" / "formcztv_init.py"


def _pm_values(text: str) -> set[int]:
    """Every PM the text branches on, in either shape.

    The C# writes ``pm == 9 || pm == 11``; the transcription collapses that to
    ``pm in (9, 11)``.  Reading only ``==`` sees the first form and half of the
    second, which manufactures a diff out of a faithful copy -- that mistake is
    why this helper is shared by both sides rather than written twice.
    """
    found = {int(n) for n in re.findall(r"\bpm\s*==\s*(\d+)", text)}
    for group in re.findall(r"\bpm\s+in\s*\(([0-9,\s]+)\)", text):
        found.update(int(n) for n in re.findall(r"\d+", group))
    return found


def _executable_lines(source: str) -> str:
    """The transcription's CODE, minus comments and citation strings.

    ``st.hit(...)`` lines quote the C# condition as human-readable text, so
    counting them would let a branch that is only *described* pass as a branch
    that is *implemented*.
    """
    return "".join(
        line for line in source.splitlines(keepends=True)
        if not line.lstrip().startswith(("#", "st.hit", '"', "'"))
    )


def _csharp_pms() -> set[int]:
    data = json.loads(_CONTROL_FLOW.read_text(encoding="utf-8"))
    methods = data[_CS_FILE]
    init = next(m for m in methods if m["name"] == _CS_METHOD)
    return _pm_values(json.dumps(init["branches"]))


def test_control_flow_map_is_present() -> None:
    """The machine-read view of the C# is committed, not regenerated on demand.

    Without it this whole file would skip, and a gate that skips is a gate
    that is not there.
    """
    assert _CONTROL_FLOW.is_file(), (
        f"{_CONTROL_FLOW} is missing — regenerate it with "
        "`python3.12 dev/decompiler/extract_control_flow.py`"
    )
    assert _csharp_pms(), (
        f"no `pm ==` branches found for {_CS_METHOD} in {_CS_FILE} — the "
        "extractor's output shape changed and this gate is now blind"
    )


def test_every_csharp_pm_branch_is_transcribed() -> None:
    """No branch exists in the C# that the transcription silently drops."""
    missing = sorted(_csharp_pms() - _pm_values(_executable_lines(
        _TRANSCRIPTION.read_text(encoding="utf-8"))))
    assert not missing, (
        f"{_CS_METHOD} branches on PM {missing} and "
        f"{_TRANSCRIPTION.name} does not. Every device audit runs against the "
        "transcription, so these panels are not 'disagreeing' — they are "
        "unrepresented, and the audit will report AGREE for them forever."
    )


def test_the_transcription_invents_no_branch() -> None:
    """And nothing is transcribed that the C# does not actually test.

    The opposite failure and the quieter one: a PM the real program never
    branches on, answered confidently by our copy of it.
    """
    extra = sorted(_pm_values(_executable_lines(
        _TRANSCRIPTION.read_text(encoding="utf-8"))) - _csharp_pms())
    assert not extra, (
        f"{_TRANSCRIPTION.name} branches on PM {extra}, which {_CS_METHOD} "
        "never tests. Our oracle would answer for hardware the C# has no "
        "opinion about."
    )


@pytest.mark.skipif(
    not _CS_SOURCE.is_file(),
    reason=f"no decompile at {DECOMPILE_ROOT} — set TRCC_DECOMPILE",
)
def test_control_flow_map_still_matches_the_live_decompile() -> None:
    """Gate the ROUND TRIP, not just the half we committed.

    ``control-flow.json`` is itself a generated artifact.  Holding the
    transcription against a stale artifact would re-create the exact failure
    this file exists to prevent, one level down.  When the decompile is on
    this machine, re-read the real ``.cs`` and confirm the committed map still
    describes it.  Absent (CI, a fresh clone), skip -- same stance as
    ``test_oracle_version``.
    """
    text = _CS_SOURCE.read_text(encoding="utf-8", errors="replace")
    start = text.index(f"{_CS_METHOD}(")
    # The method's own body only — the next member starts at one tab, and
    # ILSpy output is regularly indented (the extractor leans on this too).
    body = text[start:]
    end = re.search(r"\n\t(?:private|public|protected|internal)\s", body)
    if end:
        body = body[:end.start()]

    live = _pm_values(body)
    committed = _csharp_pms()
    assert live == committed, (
        f"control-flow.json says {_CS_METHOD} branches on PM "
        f"{sorted(committed)}, the decompile on disk says {sorted(live)}. "
        "The committed map is stale — regenerate it with "
        "`python3.12 dev/decompiler/extract_control_flow.py`."
    )
